// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cppddpkcyroxcisgshek.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNwcGRkcGtjeXJveGNpc2dzaGVrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0NzEwODUsImV4cCI6MjA3NDA0NzA4NX0.0amlersIaLMCQTqFGQL9HnlBnMPTqqSMiha_MJAybKc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});